const productDetails = {
    1: {
      id: 1,
      name: "Mondevio Silver Bead Hoop Earrings",
      price: "$50",
      description: "Stylish and elegant silver bead hoop earrings perfect for any occasion.",
      image: "/Imagess/ear3.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sterling Silver",
        dimensions: "20mm diameter",
        weight: "4g",
        origin: "Made in Italy",
      },
    },
    2: {
      id: 2,
      name: "Elegant Necklace",
      price: "$75",
      description: "A beautiful and elegant necklace to complement your outfit.",
      image: "/Imagess/Necklaces/neck1.jpg",
      category: "necklace",
      additionalInfo: {
        material: "Gold-plated",
        length: "18 inches",
        weight: "10g",
        origin: "Made in France",
      },
    },
    3: {
      id: 3,
      name: "Infinity X.O Diamond Ring in Sterling Silver",
      price: "$200",
      description: "A luxurious gold ring that adds a touch of class to any attire.",
      image: "/Imagess/Rings/ring2.jpg",
      category: "ring",
      additionalInfo: {
        material: "18K Gold",
        size: "7",
        weight: "5g",
        origin: "Made in USA",
      },
    },
    4: {
      id: 4,
      name: "Bliss Golden Ring",
      price: "$150",
      description: "A luxurious gold ring that adds a touch of class to any attire.",
      image: "/Imagess/Rings/ring1.jpg",
      category: "ring",
      additionalInfo: {
        material: "18K Gold",
        size: "7",
        weight: "5g",
        origin: "Made in USA",
      },
    },
    5: {
      id: 5,
      name: "Fine Indian Sterling Emerald-cut Ring",
      price: "$499.00",
      description: "A luxurious gold ring that adds a touch of class to any attire.",
      image: "/Imagess/Rings/ring3.jpg",
      category: "ring",
      additionalInfo: {
        material: "18K Gold",
        size: "7",
        weight: "5g",
        origin: "Made in USA",
      },
    },
    6: {
      id: 6,
      name: "Designs Sterling Silver Diamond Accent Earrings",
      price: "$190",
      description: "Stylish and elegant silver bead hoop earrings perfect for any occasion.",
      image: "/Imagess/ear1.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sterling Silver",
        dimensions: "20mm diameter",
        weight: "4g",
        origin: "Made in Italy",
      },
    },
    7: {
      id: 7,
      name: "Goldplated Crystal Flower Leverback Earrings",
      price: "$250",
      description: "Stylish and elegant silver bead hoop earrings perfect for any occasion.",
      image: "/Imagess/ear2.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sterling Silver",
        dimensions: "20mm diameter",
        weight: "4g",
        origin: "Made in Italy",
      },
    },
    8: {
      id: 8,
      name: "Round Fiery Created Pink Opal Stud Earrings",
      price: "$150",
      description: "Stylish and elegant silver bead hoop earrings perfect for any occasion.",
      image: "/Imagess/ear4.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sterling Silver",
        dimensions: "20mm diameter",
        weight: "4g",
        origin: "Made in Italy",
      },
    },
    // Additional earrings
    9: {
      id: 9,
      name: "Vintage Pearl Drop Earrings",
      price: "$80",
      description: "Classic pearl drop earrings with a vintage touch.",
      image: "/Imagess/ear5.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Freshwater Pearls",
        dimensions: "30mm drop",
        weight: "6g",
        origin: "Made in Japan",
      },
    },
    10: {
      id: 10,
      name: "Art Deco Diamond Stud Earrings",
      price: "$300",
      description: "Art Deco inspired diamond stud earrings with a timeless design.",
      image: "/Imagess/ear6.jpg",
      category: "earrings",
      additionalInfo: {
        material: "18K White Gold and Diamonds",
        dimensions: "10mm",
        weight: "8g",
        origin: "Made in Switzerland",
      },
    },
    11: {
      id: 11,
      name: "Bohemian Tassel Earrings",
      price: "$120",
      description: "Trendy bohemian tassel earrings for a chic look.",
      image: "/Imagess/ear7.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Cotton and Metal",
        dimensions: "40mm tassel",
        weight: "5g",
        origin: "Made in India",
      },
    },
    12: {
      id: 12,
      name: "Geometric Gold Hoop Earrings",
      price: "$90",
      description: "Modern geometric gold hoop earrings with a sleek finish.",
      image: "/Imagess/ear8.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Gold-plated",
        dimensions: "25mm diameter",
        weight: "4g",
        origin: "Made in Italy",
      },
    },
    13: {
      id: 13,
      name: "Crystal Chandelier Earrings",
      price: "$160",
      description: "Elegant crystal chandelier earrings for a glamorous look.",
      image: "/Imagess/ear9.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Crystal and Gold",
        dimensions: "50mm length",
        weight: "7g",
        origin: "Made in Austria",
      },
    },
    14: {
      id: 14,
      name: "Gold and Onyx Drop Earrings",
      price: "$130",
      description: "Sophisticated gold and onyx drop earrings for a modern touch.",
      image: "/Imagess/ear10.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Gold and Onyx",
        dimensions: "35mm drop",
        weight: "6g",
        origin: "Made in USA",
      },
    },
    15: {
      id: 15,
      name: "Turquoise Stud Earrings",
      price: "$70",
      description: "Bright and vibrant turquoise stud earrings to add a pop of color.",
      image: "/Imagess/ear11.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Turquoise and Sterling Silver",
        dimensions: "8mm",
        weight: "3g",
        origin: "Made in Mexico",
      },
    },
    16: {
      id: 16,
      name: "Sapphire and Diamond Hoop Earrings",
      price: "$250",
      description: "Elegant sapphire and diamond hoop earrings with a luxurious feel.",
      image: "/Imagess/ear12.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sapphire and Diamonds",
        dimensions: "20mm diameter",
        weight: "6g",
        origin: "Made in UK",
      },
    },
    17: {
      id: 17,
      name: "Elegant Ruby Drop Earrings",
      price: "$220",
      description: "Sophisticated ruby drop earrings perfect for special occasions.",
      image: "/Imagess/ear13.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Rubies and Gold",
        dimensions: "30mm drop",
        weight: "5g",
        origin: "Made in Sri Lanka",
      },
    },
    18: {
      id: 18,
      name: "Hollow Heart Earrings",
      price: "$85",
      description: "Cute hollow heart earrings that add a touch of love to any outfit.",
      image: "/Imagess/ear14.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Gold-plated",
        dimensions: "15mm heart",
        weight: "3g",
        origin: "Made in Italy",
      },
    },
    19: {
      id: 19,
      name: "Minimalist Silver Stud Earrings",
      price: "$60",
      description: "Simple and elegant minimalist silver stud earrings for everyday wear.",
      image: "/Imagess/ear15.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Sterling Silver",
        dimensions: "6mm",
        weight: "2g",
        origin: "Made in Germany",
      },
    },
    20: {
      id: 20,
      name: "Vintage Inspired Drop Earrings",
      price: "$110",
      description: "Vintage-inspired drop earrings with intricate designs and high-quality materials.",
      image: "/Imagess/ear16.jpg",
      category: "earrings",
      additionalInfo: {
        material: "Gold and Enamel",
        dimensions: "40mm drop",
        weight: "6g",
        origin: "Made in France",
      },
    },
    21: {
        id: 21,
        name: "Classic Pearl Necklace",
        price: "$120",
        description: "Timeless pearl necklace perfect for elegant occasions.",
        image: "/Imagess/Necklaces/neck2.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Freshwater Pearls",
            length: "20 inches",
            weight: "12g",
            origin: "Made in Japan",
        },
    },
    22: {
        id: 22,
        name: "Emerald Pendant Necklace",
        price: "$250",
        description: "Elegant emerald pendant on a gold chain, perfect for special events.",
        image: "/Imagess/Necklaces/neck3.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Gold and Emerald",
            length: "18 inches",
            weight: "8g",
            origin: "Made in India",
        },
    },
    23: {
        id: 23,
        name: "Diamond Heart Necklace",
        price: "$300",
        description: "Beautiful diamond-studded heart pendant on a silver chain.",
        image: "/Imagess/Necklaces/neck4.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Sterling Silver and Diamonds",
            length: "16 inches",
            weight: "10g",
            origin: "Made in Italy",
        },
    },
    24: {
        id: 24,
        name: "Sapphire Choker Necklace",
        price: "$270",
        description: "Stunning sapphire choker necklace with an intricate design.",
        image: "/Imagess/Necklaces/neck5.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Sapphire and Gold",
            length: "14 inches",
            weight: "15g",
            origin: "Made in UK",
        },
    },
    25: {
        id: 25,
        name: "Ruby Drop Necklace",
        price: "$240",
        description: "Elegant ruby drop necklace perfect for evening wear.",
        image: "/Imagess/Necklaces/neck6.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Gold and Ruby",
            length: "18 inches",
            weight: "9g",
            origin: "Made in Sri Lanka",
        },
    },
    26: {
        id: 26,
        name: "Turquoise Bead Necklace",
        price: "$100",
        description: "Bohemian-style turquoise bead necklace for a vibrant look.",
        image: "/Imagess/Necklaces/neck7.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Turquoise and Sterling Silver",
            length: "24 inches",
            weight: "14g",
            origin: "Made in Mexico",
        },
    },
    27: {
        id: 27,
        name: "Gold-Plated Infinity Necklace",
        price: "$140",
        description: "Modern infinity necklace with a sleek gold-plated design.",
        image: "/Imagess/Necklaces/neck8.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Gold-plated",
            length: "20 inches",
            weight: "8g",
            origin: "Made in USA",
        },
    },
    28: {
        id: 28,
        name: "Rose Gold Bar Necklace",
        price: "$110",
        description: "Minimalist rose gold bar necklace for a chic everyday look.",
        image: "/Imagess/Necklaces/neck9.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Rose Gold",
            length: "18 inches",
            weight: "5g",
            origin: "Made in France",
        },
    },
    29: {
        id: 29,
        name: "Opal Teardrop Necklace",
        price: "$200",
        description: "Delicate opal teardrop necklace with a sparkling finish.",
        image: "/Imagess/Necklaces/neck10.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Opal and Sterling Silver",
            length: "18 inches",
            weight: "8g",
            origin: "Made in Australia",
        },
    },
    30: {
        id: 30,
        name: "Vintage Locket Necklace",
        price: "$180",
        description: "Charming vintage locket necklace with intricate engravings.",
        image: "/Imagess/Necklaces/neck11.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Gold-plated",
            length: "24 inches",
            weight: "12g",
            origin: "Made in UK",
        },
    },
    31: {
        id: 31,
        name: "Geometric Silver Necklace",
        price: "$130",
        description: "Modern geometric silver necklace for a bold statement.",
        image: "/Imagess/Necklaces/neck12.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Sterling Silver",
            length: "20 inches",
            weight: "10g",
            origin: "Made in Germany",
        },
    },
    32: {
        id: 32,
        name: "Crystal Flower Necklace",
        price: "$210",
        description: "Elegant crystal flower necklace for a touch of glamour.",
        image: "/Imagess/Necklaces/neck13.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Crystal and Sterling Silver",
            length: "18 inches",
            weight: "7g",
            origin: "Made in Austria",
        },
    },
    33: {
        id: 33,
        name: "Bohemian Feather Necklace",
        price: "$90",
        description: "Stylish bohemian feather necklace with earthy tones.",
        image: "/Imagess/Necklaces/neck14.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Feathers and Leather",
            length: "26 inches",
            weight: "10g",
            origin: "Made in USA",
        },
    },
    34: {
        id: 34,
        name: "Infinity Pearl Necklace",
        price: "$150",
        description: "Elegant infinity pearl necklace with a modern twist.",
        image: "/Imagess/Necklaces/neck15.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Freshwater Pearls and Gold",
            length: "18 inches",
            weight: "9g",
            origin: "Made in Japan",
        },
    },
    35: {
        id: 35,
        name: "Gemstone Cluster Necklace",
        price: "$230",
        description: "Vibrant gemstone cluster necklace with multiple colors.",
        image: "/Imagess/Necklaces/neck16.jpg",
        category: "necklace",
        additionalInfo: {
            material: "Gold and Various Gemstones",
            length: "20 inches",
            weight: "15g",
            origin: "Made in India",
        },
    },
    36: {
        id: 36,
        name: "Vintage Sapphire Ring",
        price: "$350",
        description: "An exquisite vintage sapphire ring that exudes elegance.",
        image: "/Imagess/Rings/ring4.jpg",
        category: "ring",
        additionalInfo: {
            material: "18K White Gold and Sapphire",
            size: "6",
            weight: "5g",
            origin: "Made in UK",
        },
    },
    37: {
        id: 37,
        name: "Emerald Cut Diamond Ring",
        price: "$500",
        description: "A stunning emerald-cut diamond ring perfect for engagements.",
        image: "/Imagess/Rings/ring5.jpg",
        category: "ring",
        additionalInfo: {
            material: "Platinum and Diamond",
            size: "7",
            weight: "6g",
            origin: "Made in USA",
        },
    },
    38: {
        id: 38,
        name: "Rose Gold Infinity Ring",
        price: "$180",
        description: "A delicate rose gold infinity ring symbolizing eternal love.",
        image: "/Imagess/Rings/ring6.jpg",
        category: "ring",
        additionalInfo: {
            material: "14K Rose Gold",
            size: "6.5",
            weight: "3g",
            origin: "Made in Italy",
        },
    },
    39: {
        id: 39,
        name: "Black Onyx Men's Ring",
        price: "$220",
        description: "Bold black onyx ring designed for the modern man.",
        image: "/Imagess/Rings/ring7.jpg",
        category: "ring",
        additionalInfo: {
            material: "Sterling Silver and Onyx",
            size: "10",
            weight: "8g",
            origin: "Made in Germany",
        },
    },
    40: {
        id: 40,
        name: "Ruby Halo Ring",
        price: "$400",
        description: "A breathtaking ruby halo ring surrounded by sparkling diamonds.",
        image: "/Imagess/Rings/ring8.jpg",
        category: "ring",
        additionalInfo: {
            material: "18K Gold, Ruby, and Diamonds",
            size: "7.5",
            weight: "5g",
            origin: "Made in Sri Lanka",
        },
    },
    41: {
        id: 41,
        name: "Celtic Knot Band",
        price: "$130",
        description: "A beautifully crafted Celtic knot band symbolizing unity.",
        image: "/Imagess/Rings/ring9.jpg",
        category: "ring",
        additionalInfo: {
            material: "Sterling Silver",
            size: "8",
            weight: "4g",
            origin: "Made in Ireland",
        },
    },
    42: {
        id: 42,
        name: "Pearl Adjustable Ring",
        price: "$160",
        description: "Elegant adjustable ring adorned with a lustrous pearl.",
        image: "/Imagess/Rings/ring10.jpg",
        category: "ring",
        additionalInfo: {
            material: "14K Gold and Freshwater Pearl",
            size: "Adjustable",
            weight: "3g",
            origin: "Made in Japan",
        },
    },
    43: {
        id: 43,
        name: "Turquoise Bohemian Ring",
        price: "$90",
        description: "Vibrant turquoise ring perfect for a bohemian look.",
        image: "/Imagess/Rings/ring11.jpg",
        category: "ring",
        additionalInfo: {
            material: "Sterling Silver and Turquoise",
            size: "7",
            weight: "5g",
            origin: "Made in Mexico",
        },
    },
    44: {
        id: 44,
        name: "Minimalist Gold Band",
        price: "$120",
        description: "Simple and elegant gold band suitable for everyday wear.",
        image: "/Imagess/Rings/ring12.jpg",
        category: "ring",
        additionalInfo: {
            material: "18K Gold",
            size: "6",
            weight: "4g",
            origin: "Made in France",
        },
    },
    45: {
        id: 45,
        name: "Amethyst Cocktail Ring",
        price: "$250",
        description: "Eye-catching amethyst cocktail ring for special occasions.",
        image: "/Imagess/Rings/ring13.jpg",
        category: "ring",
        additionalInfo: {
            material: "Sterling Silver and Amethyst",
            size: "7",
            weight: "6g",
            origin: "Made in Brazil",
        },
    },
    46: {
        id: 46,
        name: "Men's Titanium Band",
        price: "$140",
        description: "Durable and sleek titanium band designed for men.",
        image: "/Imagess/Rings/ring14.jpg",
        category: "ring",
        additionalInfo: {
            material: "Titanium",
            size: "11",
            weight: "5g",
            origin: "Made in USA",
        },
    },
    47: {
        id: 47,
        name: "Opal Vintage Ring",
        price: "$300",
        description: "A mesmerizing opal ring with vintage-inspired designs.",
        image: "/Imagess/Rings/ring15.jpg",
        category: "ring",
        additionalInfo: {
            material: "14K Gold and Opal",
            size: "6.5",
            weight: "5g",
            origin: "Made in Australia",
        },
    },
  };
  
  export default productDetails;
  